### ISSUE TITLE
How to run a global listener in Svelte in Capacitor?

### ISSUE THREAD

**Issue by bluepuma77** [khromov/sveltekit-capacitor-starter#5]
I am trying to get [Capacitor Push Notifications](https://capacitorjs.com/docs/next/apis/push-notifications) to run. Later silent push notifications and Siri Shortcuts actions with automation.

Have you continued to work with SvelteKit/Capacitor and can recommend where to centrally place something like `addListener()` ([example](https://capacitorjs.com/docs/next/apis/push-notifications#example)) for global use in Svelte?

**Comment by khromov** [comment]
You can put the listeners in the root layout `src/routes/+layout.svelte`. Typically the root layout doesn't remount so it only runs once per "app open". After that it depends a bit on your application structure. I had a somewhat complex structure where my application could register a callback (stored in a store) from anywhere to trigger on these listeners, so for example my `pushNotificationReceived` listener in root layout was:

```ts
await PushNotifications.addListener('pushNotificationReceived', (notification) => {
		const callback = get(nativeNotificationReceivedCallback); // this is a store
		callback(notification);
	});
```

Then a bit later in my app I could register a callback for this event from anywhere in my app, like:

```ts
nativeNotificationReceivedCallback.set(async (notification) => { 
    toast.success(notification.title, { icon: '🌱' });
    console.log('Push notification received: ', notification);
});
```

I think this is perhaps a little overengineered but it made it easier for the registration code to live in a dedicated Svelte component rather than in the root layout. 

I don't know anything about silent push or Siri, but it should work the same except for a few limitations that are OS-dependent.

Hope it helps.

**Comment by bluepuma77** [comment]
@khromov Thanks a lot for the extensive answer! 🥳
