### ISSUE TITLE
Bunjs instead of nodejs

### ISSUE THREAD

**Issue by geoman2** [khromov/sveltekit-capacitor-starter#8]
Hi Stanislav

What do you think about replacing nodejs with bunjs at least for GHA build, can you test if it is really so fast? Bunjs is enhancing every day and is nodejs compatible (a lot of nodejs packages are successfully run on bun in the last months)

**Comment by khromov** [comment]
You are welcome to fork the repo and try replacing Node.js with Bun.

In general I don't see much use for Bun with Capacitor projects because the runtime is only used for building the app, so at best you'd be improving your build times by a few seconds over Node. There's no runtime performance increase.
